name: CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm run typecheck
